# Generated by Django 4.0.1 on 2022-04-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mark',
            field=models.CharField(default='Apple', max_length=50),
            preserve_default=False,
        ),
    ]
