# Generated by Django 4.0.1 on 2022-04-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mark',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
