# Generated by Django 4.0.4 on 2022-06-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_category_product_available_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(to='core.category'),
        ),
    ]
