# Generated by Django 4.0.4 on 2022-06-17 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_category_sub_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('gpu_memory', models.CharField(max_length=50)),
                ('TDP', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LaptopCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee_mounth', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('operational_system', models.CharField(max_length=30)),
                ('cpu', models.CharField(max_length=50)),
                ('batery', models.CharField(max_length=50)),
                ('screen_diagonal', models.DecimalField(decimal_places=1, max_digits=5)),
                ('gpu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gpu')),
            ],
        ),
    ]
