# Generated by Django 4.0.4 on 2022-06-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_gpu_laptopcharacteristic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GPU',
            new_name='GPU_Characteristic',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='sub_category',
        ),
        migrations.AddField(
            model_name='laptopcharacteristic',
            name='product_connected',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
